# -*- coding: utf-8 -*-
"""Rainfall_Automated.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MFHa6eY_4pwbm7qpqINK9vBHqj-dY_Mp
"""

path='/content/drive/MyDrive/Rainfall/Rainfall_5-3-2024.csv'

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sna
import scipy.stats as stats

rainfall=pd.read_csv(r'/content/drive/MyDrive/Rainfall/Rainfall_5-3-2024.csv')

rainfall=rainfall.astype('category')
rainfall=rainfall.T
rainfall=rainfall.reset_index()
rainfall.columns=rainfall.iloc[0,:]
rainfall.drop(labels=[0],inplace=True)
rainfall_Formatted=pd.melt(rainfall,id_vars='Date(IST)                        ',var_name='date_time',value_name='Rainfall in mm')
rainfall_Formatted.replace('-',np.nan,inplace=True)
rainfall_Formatted['Rainfall in mm']=rainfall_Formatted['Rainfall in mm'].astype(float)

rainfall_Formatted

rainfall_Formatted['date_time']=pd.to_datetime(rainfall_Formatted['date_time'] ,dayfirst=True)

rainfall_Formatted['Date(IST)                        ']=rainfall_Formatted['Date(IST)                        '].astype('category')
rainfall_Formatted[['Station_Name','Station Code','State','District','Tehsil','Block','Village']]=rainfall_Formatted['Date(IST)                        '].str.split('\n',expand=True).astype('category')
rainfall_Formatted.drop(columns=['Date(IST)                        ','Tehsil','Block','Village','State'],inplace=True)
rainfall_Formatted=rainfall_Formatted[['Station Code','Station_Name','District','date_time','Rainfall in mm']]

rainfall_Formatted['Station Code']=rainfall_Formatted['Station Code'].astype(str)
rainfall_Formatted['Station_Name']=rainfall_Formatted['Station_Name'].astype(str)
rainfall_Formatted['District']=rainfall_Formatted['District'].astype(str)

rainfall_Formatted['Station_Name']=rainfall_Formatted['Station_Name'].astype(str)

rainfall_Formatted.replace('Station Name:','',regex=True,inplace=True)
rainfall_Formatted.replace('Station Code','',regex=True,inplace=True)
rainfall_Formatted.replace('District','',regex=True,inplace=True)
rainfall_Formatted.replace(':','',regex=True,inplace=True)

rainfall_Formatted.replace(':','',regex=True,inplace=True)
rainfall_Formatted['Station Code']=rainfall_Formatted['Station Code'].str.strip()
rainfall_Formatted[rainfall_Formatted['Station_Name'].str.contains('Kusarma')]['Station Code']

Atal_DWLR=pd.read_csv('/content/drive/MyDrive/Rainfall/Atal_DWLR.csv')

Rainfall_Januaray=Atal_DWLR.merge(rainfall_Formatted,left_on='Data Logger ID',right_on='Station Code',how='left')

Rainfall_Januaray.to_csv('/content/drive/MyDrive/Rainfall/Rain_fall.csv')